node
{
    stage('Checkout')
    {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/ambalbek/trash']]])
    }
    stage('Test')
    {
        echo 'this my pipeline for you bitches!'
    }
    stage('python')
    {
       sh label: '', script: '''cd /var/lib/jenkins/workspace/docker-pipeline/other_projects_jenkins_git
ls -al
python3 *.py'''
    }
    stage('docker')
    {
        sh label: '', script: '''docker run centos
aws ecr get-login --no-include-email --region us-east-2 > ./login
source ./login
docker tag centos:latest 440414308601.dkr.ecr.us-east-2.amazonaws.com/ambalbek:latest
docker push 440414308601.dkr.ecr.us-east-2.amazonaws.com/ambalbek:latest'''
    }
}
