node
{
    stage('Checkout')
    {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/ambalbek/trash']]])
    }
    stage('Test')
    {
        echo 'this my pipeline for you bitches!'
    }
    stage('python')
    {
       sh label: '', script: '''cd /var/lib/jenkins/workspace/mypipe/other_projects_jenkins_git
ls -al
python3 *.py'''
    }
    stage('email')
    {
        mail bcc: '', body: 'this is the result', cc: 'a.turganbaeva1@gmail.com', from: '', replyTo: '', subject: 'pipeline test', to: 'azal88@gmail.com'
    }
}